

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AddNewPass extends javax.swing.JFrame {

    /**
     * Creates new form AddNewPass
     */
    public AddNewPass() {
        initComponents();
        //To display login page in center of screen
        this.setLocationRelativeTo(null);
        //Testing accessibility of UserID
        System.out.println(Dashboard.UserId); //Successfull
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        SiteNameLabel_AddPassPage = new javax.swing.JLabel();
        SiteNameTextField_AddPassPage = new javax.swing.JTextField();
        UsernameLabel_AddPassPage = new javax.swing.JLabel();
        UsernameTextField_AddPassPage = new javax.swing.JTextField();
        PasswordLabel_AddPassPage = new javax.swing.JLabel();
        PasswordTextField_AddPassPage = new javax.swing.JTextField();
        URLLabel_AddPassPage = new javax.swing.JLabel();
        URLTxtField_AddPassPage = new javax.swing.JTextField();
        AddNewPassButton = new javax.swing.JButton();
        backButton_AddPassPage = new javax.swing.JButton();
        NoteTextField_AddPassPage = new javax.swing.JTextField();
        NoteLabel_AddPassPage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(137, 148, 108));

        jPanel2.setBackground(new java.awt.Color(85, 162, 135));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SiteNameLabel_AddPassPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SiteNameLabel_AddPassPage.setForeground(new java.awt.Color(255, 255, 255));
        SiteNameLabel_AddPassPage.setText("Site Name");
        jPanel1.add(SiteNameLabel_AddPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 35));
        jPanel1.add(SiteNameTextField_AddPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 88, 250, 35));

        UsernameLabel_AddPassPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UsernameLabel_AddPassPage.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel_AddPassPage.setText("Username");
        jPanel1.add(UsernameLabel_AddPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 35));

        UsernameTextField_AddPassPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextField_AddPassPageActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameTextField_AddPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 149, 250, 35));

        PasswordLabel_AddPassPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PasswordLabel_AddPassPage.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel_AddPassPage.setText("Password");
        jPanel1.add(PasswordLabel_AddPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 210, 90, 36));
        jPanel1.add(PasswordTextField_AddPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 211, 250, 35));

        URLLabel_AddPassPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        URLLabel_AddPassPage.setForeground(new java.awt.Color(255, 255, 255));
        URLLabel_AddPassPage.setText("URL");
        jPanel1.add(URLLabel_AddPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, 35));
        jPanel1.add(URLTxtField_AddPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 277, 250, 35));

        AddNewPassButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddNewPassButton.setText("Add");
        AddNewPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewPassButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddNewPassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 403, 250, 35));

        backButton_AddPassPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backButton_AddPassPage.setText("Back");
        backButton_AddPassPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton_AddPassPageActionPerformed(evt);
            }
        });
        jPanel1.add(backButton_AddPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 403, 80, 35));
        jPanel1.add(NoteTextField_AddPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 341, 250, 35));

        NoteLabel_AddPassPage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NoteLabel_AddPassPage.setForeground(new java.awt.Color(255, 255, 255));
        NoteLabel_AddPassPage.setText("Note");
        jPanel1.add(NoteLabel_AddPassPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 90, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 25, -1, 37));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vault-update-1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 390, 460));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vault-update-1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -160, 1200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JFrame showmsg = new JFrame();
    private void UsernameTextField_AddPassPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextField_AddPassPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextField_AddPassPageActionPerformed

    private void backButton_AddPassPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton_AddPassPageActionPerformed
        // TODO add your handling code here:
        Dashboard dashBoardPage = new Dashboard(Dashboard.UserId);//Check if this creates problem in program
        setVisible(false);  //set this current window as false
        dashBoardPage.setVisible(true);
    }//GEN-LAST:event_backButton_AddPassPageActionPerformed

    private void AddNewPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewPassButtonActionPerformed
        // TODO add your handling code here:
        String SiteName = SiteNameTextField_AddPassPage.getText();
        String username = UsernameTextField_AddPassPage.getText();
        String pass = PasswordTextField_AddPassPage.getText();
        String Url = URLTxtField_AddPassPage.getText();
        String note = NoteTextField_AddPassPage.getText();
        try {
            
            //Condition to check if there's no input
            if (SiteName.isEmpty() & username.isEmpty() & pass.isEmpty() & Url.isEmpty() & note.isEmpty()) {
                JOptionPane.showMessageDialog(showmsg, "Please Enter details.");
            }else if (SiteName.isEmpty()) {
                JOptionPane.showMessageDialog(showmsg, "Please Enter Name of Site.");
            }else if (username.isEmpty()) {
                JOptionPane.showMessageDialog(showmsg, "Please Enter the username for this site.");
            }else if (pass.isEmpty()) {
                JOptionPane.showMessageDialog(showmsg, "Please Enter the password for this site.");
            }
            else {
                Konnect k = new Konnect();
                System.out.println("Before creating query.");
                String addPassQuery = "insert into credentials values ('"+Dashboard.UserId + "','"  + SiteName + "','" + username + "','" + pass + "','" + Url + "','" + note + "')";
                System.out.println("after creating query passing it.");
                k.stm.executeUpdate(addPassQuery);  //here
                System.out.println("After executing query.");
                System.out.println("Credentials added successfully.");
                JOptionPane.showMessageDialog(showmsg, "Details added successfully.");
                SiteNameTextField_AddPassPage.setText("");
                UsernameTextField_AddPassPage.setText("");
                PasswordTextField_AddPassPage.setText("");
                URLTxtField_AddPassPage.setText("");
                NoteTextField_AddPassPage.setText("");
            }

        } catch (Exception e) {
            System.out.println("Message:");
            System.out.println("Exception: " + e.getMessage());
            System.out.println("Exception trace:");
            System.out.println(e);
        }
    }//GEN-LAST:event_AddNewPassButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewPassButton;
    private javax.swing.JLabel NoteLabel_AddPassPage;
    private javax.swing.JTextField NoteTextField_AddPassPage;
    private javax.swing.JLabel PasswordLabel_AddPassPage;
    private javax.swing.JTextField PasswordTextField_AddPassPage;
    private javax.swing.JLabel SiteNameLabel_AddPassPage;
    private javax.swing.JTextField SiteNameTextField_AddPassPage;
    private javax.swing.JLabel URLLabel_AddPassPage;
    private javax.swing.JTextField URLTxtField_AddPassPage;
    private javax.swing.JLabel UsernameLabel_AddPassPage;
    private javax.swing.JTextField UsernameTextField_AddPassPage;
    private javax.swing.JButton backButton_AddPassPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
