

import java.awt.Color;
import javax.swing.JFrame;
import java.sql.*;
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public static int UserId;
    public Dashboard(int id) {
        initComponents();
        //Fetching userId (for executing quries accordingly)
        UserId = id;
    //To test the visibilty of panels when dsashboard is opened
//        PanelForAddPass.setVisible(false);
//        PanelForGeneratePass.setVisible(false);
//        PanelForSearch.setVisible(false);
//        PanelForUpdatePass.setVisible(false);
        //Testing for full screen
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        //this.setUndecorated(true);    //This will throw exception
        //To display login page in center of screen
        this.setLocationRelativeTo(null);
        //Frame for all JOptionPanes
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddPasswordTitlePanel = new javax.swing.JPanel();
        dashboardTitlelabel1 = new javax.swing.JLabel();
        GeneratePassPanelTitle = new javax.swing.JPanel();
        GeneratePassLabel = new javax.swing.JLabel();
        SearchTitlePanel = new javax.swing.JPanel();
        SearchPassLabel = new javax.swing.JLabel();
        LogutPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashboardTitlelabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 127, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPasswordTitlePanel.setBackground(new java.awt.Color(204, 204, 204));
        AddPasswordTitlePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPasswordTitlePanelMouseClicked(evt);
            }
        });

        dashboardTitlelabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dashboardTitlelabel1.setText("Add Password");
        dashboardTitlelabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dashboardTitlelabel1MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout AddPasswordTitlePanelLayout = new javax.swing.GroupLayout(AddPasswordTitlePanel);
        AddPasswordTitlePanel.setLayout(AddPasswordTitlePanelLayout);
        AddPasswordTitlePanelLayout.setHorizontalGroup(
            AddPasswordTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPasswordTitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboardTitlelabel1)
                .addGap(54, 54, 54))
        );
        AddPasswordTitlePanelLayout.setVerticalGroup(
            AddPasswordTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTitlelabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel1.add(AddPasswordTitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 223, -1));

        GeneratePassPanelTitle.setBackground(new java.awt.Color(204, 204, 204));
        GeneratePassPanelTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeneratePassPanelTitleMouseClicked(evt);
            }
        });

        GeneratePassLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        GeneratePassLabel.setText("Generate Password");

        javax.swing.GroupLayout GeneratePassPanelTitleLayout = new javax.swing.GroupLayout(GeneratePassPanelTitle);
        GeneratePassPanelTitle.setLayout(GeneratePassPanelTitleLayout);
        GeneratePassPanelTitleLayout.setHorizontalGroup(
            GeneratePassPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneratePassPanelTitleLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(GeneratePassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        GeneratePassPanelTitleLayout.setVerticalGroup(
            GeneratePassPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GeneratePassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel1.add(GeneratePassPanelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        SearchTitlePanel.setBackground(new java.awt.Color(204, 204, 204));
        SearchTitlePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchTitlePanelMouseClicked(evt);
            }
        });

        SearchPassLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SearchPassLabel.setText("Search");

        javax.swing.GroupLayout SearchTitlePanelLayout = new javax.swing.GroupLayout(SearchTitlePanel);
        SearchTitlePanel.setLayout(SearchTitlePanelLayout);
        SearchTitlePanelLayout.setHorizontalGroup(
            SearchTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchTitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        SearchTitlePanelLayout.setVerticalGroup(
            SearchTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SearchPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel1.add(SearchTitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 223, -1));

        LogutPanel.setBackground(new java.awt.Color(204, 204, 204));
        LogutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogutPanelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Logut");

        javax.swing.GroupLayout LogutPanelLayout = new javax.swing.GroupLayout(LogutPanel);
        LogutPanel.setLayout(LogutPanelLayout);
        LogutPanelLayout.setHorizontalGroup(
            LogutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogutPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogutPanelLayout.setVerticalGroup(
            LogutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel1.add(LogutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 223, -1));

        dashboardTitlelabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        dashboardTitlelabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardTitlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardTitlelabel.setText("Dashboard");
        jPanel1.add(dashboardTitlelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 200, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vault-update-1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-440, -110, 770, 800));

        Panel.setBackground(new java.awt.Color(93, 240, 127));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("WELCOME TO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 230, 70));

        jLabel6.setFont(new java.awt.Font("Sitka Heading", 3, 54)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DIGITAL VAULT");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vault-update-1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -130, 600, 840));

        Panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JFrame showMsg = new JFrame();
    private void AddPasswordTitlePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPasswordTitlePanelMouseClicked
        // TODO add your handling code here:
        AddNewPass AddPasswordPage = new AddNewPass();
        setVisible(false);
        AddPasswordPage.setVisible(true);
        
        //To set white color of panel, when clicked
        AddPasswordTitlePanel.setBackground(Color.white);
        //Same color for others panels
        //UpdatePassTitlePanel.setBackground(new Color(204,204,204));
        GeneratePassPanelTitle.setBackground(new Color(204,204,204));
        SearchTitlePanel.setBackground(new Color(204,204,204));
        
    }//GEN-LAST:event_AddPasswordTitlePanelMouseClicked

    private void GeneratePassPanelTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeneratePassPanelTitleMouseClicked
        // TODO add your handling code here:
        GeneratePassword randomPasswordPage = new GeneratePassword();
        setVisible(false);
        randomPasswordPage.setVisible(true);
        
        //To set white color of panel, when clicked
        GeneratePassPanelTitle.setBackground(Color.white);
        //Same color for others panels        
        //UpdatePassTitlePanel.setBackground(new Color(204,204,204));
        AddPasswordTitlePanel.setBackground(new Color(204,204,204));
        SearchTitlePanel.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_GeneratePassPanelTitleMouseClicked

    private void SearchTitlePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTitlePanelMouseClicked
        // TODO add your handling code here:
        SearchPassword searchPass = new SearchPassword();
        setVisible(false);
        searchPass.setVisible(true);
        //To set white color of panel, when clicked
        SearchTitlePanel.setBackground(Color.white);
        //Same color for others panels        
        GeneratePassPanelTitle.setBackground(new Color(204,204,204));
        //UpdatePassTitlePanel.setBackground(new Color(204,204,204));
        AddPasswordTitlePanel.setBackground(new Color(204,204,204));

    }//GEN-LAST:event_SearchTitlePanelMouseClicked

    private void LogutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogutPanelMouseClicked
        // TODO add your handling code here:
        //close connection
        //try{
            //kon.close();
        //}
//        catch(SQLException e){
//            System.out.println("SQL Exception: "+e.getMessage());
//        }
        
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_LogutPanelMouseClicked

    private void dashboardTitlelabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardTitlelabel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardTitlelabel1MouseDragged
    
    int PassLength; //By default length when textfield is empty
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard(23).setVisible(true); //Commented to test id 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPasswordTitlePanel;
    private javax.swing.JLabel GeneratePassLabel;
    private javax.swing.JPanel GeneratePassPanelTitle;
    private javax.swing.JPanel LogutPanel;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel SearchPassLabel;
    private javax.swing.JPanel SearchTitlePanel;
    private javax.swing.JLabel dashboardTitlelabel;
    private javax.swing.JLabel dashboardTitlelabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
