

import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class GeneratePassword extends javax.swing.JFrame {

    /**
     * Creates new form GeneratePassword
     */
    public GeneratePassword() {
        initComponents();
        //To display login page in center of screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PasslengthTxtField_generatePass = new javax.swing.JTextField();
        GeneratePassButton = new javax.swing.JButton();
        GeneratedPasswordTxtField = new javax.swing.JTextField();
        RandmPassPrintLabel = new javax.swing.JLabel();
        BackButton_GeneratePass = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        GeneratePassTitleLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(85, 162, 135));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Lenth of Password: ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 40, -1, 35));

        PasslengthTxtField_generatePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasslengthTxtField_generatePassActionPerformed(evt);
            }
        });
        jPanel2.add(PasslengthTxtField_generatePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 82, 230, 35));

        GeneratePassButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GeneratePassButton.setText("Ok");
        GeneratePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePassButtonActionPerformed(evt);
            }
        });
        jPanel2.add(GeneratePassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 230, 35));
        jPanel2.add(GeneratedPasswordTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 230, 35));

        RandmPassPrintLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RandmPassPrintLabel.setForeground(new java.awt.Color(255, 255, 255));
        RandmPassPrintLabel.setText("Password:");
        jPanel2.add(RandmPassPrintLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 115, 34));

        BackButton_GeneratePass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackButton_GeneratePass.setText("Back");
        BackButton_GeneratePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton_GeneratePassActionPerformed(evt);
            }
        });
        jPanel2.add(BackButton_GeneratePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 100, 33));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vault-update-1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -130, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 350, 400));

        GeneratePassTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        GeneratePassTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        GeneratePassTitleLabel.setText("Generate Password");
        jPanel1.add(GeneratePassTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vault-update-1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -110, 1200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 313, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int PassLength; //By default length when textfield is empty
    private void PasslengthTxtField_generatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasslengthTxtField_generatePassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasslengthTxtField_generatePassActionPerformed
    JFrame printMsg = new JFrame();
    private void BackButton_GeneratePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton_GeneratePassActionPerformed
        // TODO add your handling code here:
        Dashboard dashBoardPage = new Dashboard(Dashboard.UserId);//Check if creates problem
        setVisible(false);  //set this current window as false
        dashBoardPage.setVisible(true);
    }//GEN-LAST:event_BackButton_GeneratePassActionPerformed

    private void GeneratePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePassButtonActionPerformed
        // TODO add your handling code here:
        String alpha =  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
	String numbers = "0123456789";
	String chars  = "!@#$%^&*()_+=-?><.,|/";
	String concated = alpha+numbers+chars;
        
        int randomInt;
	char randomChar;
	String PassGenerated = "";
	Random randObj = new Random();
        try{
            //Adding input to by default length
            if (PasslengthTxtField_generatePass.getText().isEmpty()){
                JOptionPane.showMessageDialog(printMsg,"Please enter the length.");
            }
            else{
                PassLength = Integer.parseInt(PasslengthTxtField_generatePass.getText());
            if (PassLength <= 0){
                //Throw Exception 
                throw new NegativeNumberException("Length can't be Negative.");
            }
            else{
                //Continue with programme
                for (int i = 0; i < PassLength; i++){
		    randomInt = randObj.nextInt(concated.length());
		//    randomChar = concated.charAt(randomInt);
		    PassGenerated = PassGenerated + concated.charAt(randomInt);
                    GeneratedPasswordTxtField.setText(PassGenerated);
		}
            }
            }
            //JOptionPane.showMessageDialog(showMsg,"Password length is: "+PassLength);
            
        }
        catch(NegativeNumberException tooSmallLength){
            JOptionPane.showMessageDialog(printMsg,"Invalid Length for password!");
            PasslengthTxtField_generatePass.setText("");
        }
        catch(Exception strInput){
            //Show msg and empty the text field
            
            JOptionPane.showMessageDialog(printMsg,"Invalid input. Please enter Length in numbers.");
            PasslengthTxtField_generatePass.setText("");
            
        }

    }//GEN-LAST:event_GeneratePassButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneratePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneratePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneratePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneratePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneratePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton_GeneratePass;
    private javax.swing.JButton GeneratePassButton;
    private javax.swing.JLabel GeneratePassTitleLabel;
    private javax.swing.JTextField GeneratedPasswordTxtField;
    private javax.swing.JTextField PasslengthTxtField_generatePass;
    private javax.swing.JLabel RandmPassPrintLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
