

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;

public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        //To display login page in center of screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DigVaultTitleLabel_SignUp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SignUpTitleLabel = new javax.swing.JLabel();
        UsernameLabel_SignUpPage = new javax.swing.JLabel();
        UsernameTxtField_SignUpPage = new javax.swing.JTextField();
        PasswordLabel_SignUpPage = new javax.swing.JLabel();
        jPasswordField_SignUpPage = new javax.swing.JPasswordField();
        UserIdLabel_SignUpPage = new javax.swing.JLabel();
        SignUpButton_SignUpPage = new javax.swing.JButton();
        userIdTxtField_SignUpPage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vault-update-1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 132, 127));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DigVaultTitleLabel_SignUp.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        DigVaultTitleLabel_SignUp.setForeground(new java.awt.Color(255, 255, 255));
        DigVaultTitleLabel_SignUp.setText("DIGITAL VAULT");
        jPanel1.add(DigVaultTitleLabel_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 300, 60));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        SignUpTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        SignUpTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpTitleLabel.setText("SIGN UP");
        jPanel2.add(SignUpTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 25, 100, 40));

        UsernameLabel_SignUpPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernameLabel_SignUpPage.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel_SignUpPage.setText("Username");
        jPanel2.add(UsernameLabel_SignUpPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 83, 100, 30));

        UsernameTxtField_SignUpPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTxtField_SignUpPageActionPerformed(evt);
            }
        });
        jPanel2.add(UsernameTxtField_SignUpPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 120, 240, 40));

        PasswordLabel_SignUpPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordLabel_SignUpPage.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel_SignUpPage.setText("Password");
        jPanel2.add(PasswordLabel_SignUpPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 264, 80, 30));
        jPanel2.add(jPasswordField_SignUpPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 301, 240, 41));

        UserIdLabel_SignUpPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserIdLabel_SignUpPage.setForeground(new java.awt.Color(255, 255, 255));
        UserIdLabel_SignUpPage.setText("User Id:");
        jPanel2.add(UserIdLabel_SignUpPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 173, 100, 30));

        SignUpButton_SignUpPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SignUpButton_SignUpPage.setText("SIGN UP");
        SignUpButton_SignUpPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButton_SignUpPageActionPerformed(evt);
            }
        });
        jPanel2.add(SignUpButton_SignUpPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 380, 240, 37));
        jPanel2.add(userIdTxtField_SignUpPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 210, 240, 41));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vault-update-1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -140, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 370, 470));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vault-update-1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -100, 1200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JFrame showMsg = new JFrame();
    private void UsernameTxtField_SignUpPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTxtField_SignUpPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTxtField_SignUpPageActionPerformed

    private void SignUpButton_SignUpPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButton_SignUpPageActionPerformed
        // TODO add your handling code here:
        try {
            Konnect k2 = new Konnect();

            String userName = UsernameTxtField_SignUpPage.getText();
            String password = jPasswordField_SignUpPage.getText();
            System.out.println("Username is:" + userName);
            System.out.println("Password is:" + password);
            if ((userName.isEmpty()) || (password.isEmpty())) {
                throw new NoInputException("Please provide all the details.");
            } else {

                //JOptionPane.showMessageDialog(showMsg,"Please fill all the details.");
                int userId = Integer.parseInt(userIdTxtField_SignUpPage.getText());

                if (userId <= 0) {
                    throw new NegativeNumberException("User Id can't be Negative");
                }
                System.out.print("User id is: ");
                System.out.println(userId);
                
                String q3 = "insert into login values ('" + userName + "','" + userId + "','" + password + "')";
                
                k2.stm.executeUpdate(q3);
                
                setVisible(false);
                System.out.println("Before Login.");
                Login loginpage = new Login();//Null pointer Exception is here
                System.out.println("After executeUpdate.");
                loginpage.setVisible(true);

                System.out.println("Data updated successfully.");
            }

        } catch (SQLIntegrityConstraintViolationException exp) {
            //catching exception if trying to sign up with existring userid
            JOptionPane.showMessageDialog(showMsg, "Account already exists with this Id. Please Sign Up with unique Id.");
            userIdTxtField_SignUpPage.setText("");
//            jPasswordField_SignUpPage.setText("");
        } catch (NumberFormatException exp) {
            JOptionPane.showMessageDialog(showMsg, "Invalid Input. Id must be in numbers.");
        } catch (NoInputException exp) {
            JOptionPane.showMessageDialog(showMsg, "Please provide all the details.");
        } catch (NegativeNumberException exp) {
            //catch for negative number in id
            JOptionPane.showMessageDialog(showMsg, "User Id can't be negative. Please enter another Id.");
        } catch (Exception e) {
            System.out.println("Exception: " + e.getMessage());
            System.out.println("Exception: " + e);
            //System.out.println("Printing trace: "+ e.printStackTrace());
            JOptionPane.showMessageDialog(showMsg, "Invalid input. Please enter the details again.");
            UsernameTxtField_SignUpPage.setText("");
            jPasswordField_SignUpPage.setText("");
            userIdTxtField_SignUpPage.setText("");
        }
    }//GEN-LAST:event_SignUpButton_SignUpPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DigVaultTitleLabel_SignUp;
    private javax.swing.JLabel PasswordLabel_SignUpPage;
    private javax.swing.JButton SignUpButton_SignUpPage;
    private javax.swing.JLabel SignUpTitleLabel;
    private javax.swing.JLabel UserIdLabel_SignUpPage;
    private javax.swing.JLabel UsernameLabel_SignUpPage;
    private javax.swing.JTextField UsernameTxtField_SignUpPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_SignUpPage;
    private javax.swing.JTextField userIdTxtField_SignUpPage;
    // End of variables declaration//GEN-END:variables
}
