

import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;

public class UpdatePassword extends javax.swing.JFrame {

    public UpdatePassword() {
        initComponents();
        setLocationRelativeTo(null);
        /*....setting text fields to show to user.......*/
        //SiteNameTxtField_UpdatePassPanel.setText("");
        //PasswordTxtField_UpdatePassPanel.setText(pass);
    }

    public UpdatePassword(String[] arr) {
        initComponents();
        setLocationRelativeTo(null);
        //Setting values in textfields
        System.out.println("Site: " + arr[0]);
        SiteNameTxtField_UpdatePassPanel.setText(arr[0]);
        UsernameTxtField_UpdatePassPanel.setText(arr[1]);
        PasswordTxtField_UpdatePassPanel.setText(arr[2]);
        URLTxtField_UpdatePassPanel.setText(arr[3]);
        NoteTxtField_UpdatePassPanel.setText(arr[4]);
        PassStrengthLabel.setText(arr[5]);
        PassStrengthLabel.setFont(new Font("Seogoe UI",Font.BOLD, 14));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        EditPassTitleLabel = new javax.swing.JLabel();
        SiteNameLabel_UpdatePassPanel = new javax.swing.JLabel();
        SiteNameTxtField_UpdatePassPanel = new javax.swing.JTextField();
        UsernameLabel_UpdatePassPanel = new javax.swing.JLabel();
        UsernameTxtField_UpdatePassPanel = new javax.swing.JTextField();
        PasswordLabel_UpdatePassPanel = new javax.swing.JLabel();
        PasswordTxtField_UpdatePassPanel = new javax.swing.JTextField();
        URLLabel_UpdatePassPanel = new javax.swing.JLabel();
        URLTxtField_UpdatePassPanel = new javax.swing.JTextField();
        NoteLabel_UpdatePassPanel = new javax.swing.JLabel();
        NoteTxtField_UpdatePassPanel = new javax.swing.JTextField();
        UpdateButton_UpdatePassPanel = new javax.swing.JButton();
        DeleteButton_UpdatePassPanel = new javax.swing.JButton();
        BackButton_UpdatePassPanel = new javax.swing.JButton();
        StrengthLabel = new javax.swing.JLabel();
        PassStrengthLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(85, 133, 139));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditPassTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        EditPassTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        EditPassTitleLabel.setText("Edit Password");
        EditPassTitleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditPassTitleLabelMouseClicked(evt);
            }
        });
        jPanel2.add(EditPassTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 35));

        SiteNameLabel_UpdatePassPanel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SiteNameLabel_UpdatePassPanel.setForeground(new java.awt.Color(255, 255, 255));
        SiteNameLabel_UpdatePassPanel.setText("Name");
        jPanel2.add(SiteNameLabel_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 80, 80, 35));

        SiteNameTxtField_UpdatePassPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiteNameTxtField_UpdatePassPanelActionPerformed(evt);
            }
        });
        jPanel2.add(SiteNameTxtField_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 80, 211, 35));

        UsernameLabel_UpdatePassPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernameLabel_UpdatePassPanel.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel_UpdatePassPanel.setText("Username");
        jPanel2.add(UsernameLabel_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 128, 80, 35));
        jPanel2.add(UsernameTxtField_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 129, 211, 35));

        PasswordLabel_UpdatePassPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordLabel_UpdatePassPanel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel_UpdatePassPanel.setText("Password");
        jPanel2.add(PasswordLabel_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 177, 80, 35));
        jPanel2.add(PasswordTxtField_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 178, 211, 35));

        URLLabel_UpdatePassPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        URLLabel_UpdatePassPanel.setForeground(new java.awt.Color(255, 255, 255));
        URLLabel_UpdatePassPanel.setText("URL");
        jPanel2.add(URLLabel_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 274, 80, 35));
        jPanel2.add(URLTxtField_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 275, 211, 35));

        NoteLabel_UpdatePassPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NoteLabel_UpdatePassPanel.setForeground(new java.awt.Color(255, 255, 255));
        NoteLabel_UpdatePassPanel.setText("Note");
        jPanel2.add(NoteLabel_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 328, 80, 35));
        jPanel2.add(NoteTxtField_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 329, 211, 35));

        UpdateButton_UpdatePassPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateButton_UpdatePassPanel.setText("Update");
        UpdateButton_UpdatePassPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButton_UpdatePassPanelActionPerformed(evt);
            }
        });
        jPanel2.add(UpdateButton_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 382, 90, 35));

        DeleteButton_UpdatePassPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteButton_UpdatePassPanel.setText("Delete");
        DeleteButton_UpdatePassPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton_UpdatePassPanelActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteButton_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 382, 90, 35));

        BackButton_UpdatePassPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackButton_UpdatePassPanel.setText("Back");
        BackButton_UpdatePassPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton_UpdatePassPanelActionPerformed(evt);
            }
        });
        jPanel2.add(BackButton_UpdatePassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 382, 100, 35));

        StrengthLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        StrengthLabel.setForeground(new java.awt.Color(255, 255, 255));
        StrengthLabel.setText("Password Strength:");
        jPanel2.add(StrengthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 226, -1, 35));

        PassStrengthLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(PassStrengthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 226, 80, 35));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vault-update-1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -150, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 370, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vault-update-1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(1240, 800));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -150, 1200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JFrame msg = new JFrame();
    Konnect k3 = new Konnect();
    String name, UName, Pass, link, note;

    /*........Defining method here........*/

    private void EditPassTitleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditPassTitleLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditPassTitleLabelMouseClicked

    private void SiteNameTxtField_UpdatePassPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiteNameTxtField_UpdatePassPanelActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SiteNameTxtField_UpdatePassPanelActionPerformed

    private void UpdateButton_UpdatePassPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButton_UpdatePassPanelActionPerformed
        // getting all the text from textfields
        name = SiteNameTxtField_UpdatePassPanel.getText();
        UName = UsernameTxtField_UpdatePassPanel.getText();
        Pass = PasswordTxtField_UpdatePassPanel.getText();
        link = URLTxtField_UpdatePassPanel.getText();
        note = NoteTxtField_UpdatePassPanel.getText();
        //creating connection
        try {
            //SiteName shouldn't be changed.......
            k3.st.setString(1, UName);
            k3.st.setString(2, Pass);
            k3.st.setString(3, link);
            k3.st.setString(4, note);
            k3.st.setString(5, name);
            
            //Creating prepared statement
            int i = k3.st.executeUpdate();
            JOptionPane.showMessageDialog(msg, "Update Successful");
            //System.out.println("Site name is: " + name);

        } catch (Exception exp) {
            System.out.println("Exception: " + exp.getMessage());
        }
    }//GEN-LAST:event_UpdateButton_UpdatePassPanelActionPerformed

    private void DeleteButton_UpdatePassPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton_UpdatePassPanelActionPerformed
        // TODO add your handling code here:
        name = SiteNameTxtField_UpdatePassPanel.getText();
        UName = UsernameTxtField_UpdatePassPanel.getText();
        Pass = PasswordTxtField_UpdatePassPanel.getText();
        link = URLTxtField_UpdatePassPanel.getText();
        note = NoteTxtField_UpdatePassPanel.getText();
        try {
            String delete = "delete from credentials where SiteName = '" + name + "' and Username = '" + UName + "'";
            k3.stm.executeUpdate(delete);
            
            //System.out.println("Deleted....");
            JOptionPane.showMessageDialog(msg, "Deleted Successful");
        } catch (Exception exp) {
            System.out.println("Exception in delete query: " + exp);
        }
    }//GEN-LAST:event_DeleteButton_UpdatePassPanelActionPerformed

    private void BackButton_UpdatePassPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton_UpdatePassPanelActionPerformed
        // TODO add your handling code here:
        Dashboard d = new Dashboard(Dashboard.UserId);//Check if creates problem
        this.setVisible(false);
        d.setVisible(true);
    }//GEN-LAST:event_BackButton_UpdatePassPanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton_UpdatePassPanel;
    private javax.swing.JButton DeleteButton_UpdatePassPanel;
    private javax.swing.JLabel EditPassTitleLabel;
    private javax.swing.JLabel NoteLabel_UpdatePassPanel;
    private javax.swing.JTextField NoteTxtField_UpdatePassPanel;
    private javax.swing.JLabel PassStrengthLabel;
    private javax.swing.JLabel PasswordLabel_UpdatePassPanel;
    private javax.swing.JTextField PasswordTxtField_UpdatePassPanel;
    private javax.swing.JLabel SiteNameLabel_UpdatePassPanel;
    private javax.swing.JTextField SiteNameTxtField_UpdatePassPanel;
    private javax.swing.JLabel StrengthLabel;
    private javax.swing.JLabel URLLabel_UpdatePassPanel;
    private javax.swing.JTextField URLTxtField_UpdatePassPanel;
    private javax.swing.JButton UpdateButton_UpdatePassPanel;
    private javax.swing.JLabel UsernameLabel_UpdatePassPanel;
    private javax.swing.JTextField UsernameTxtField_UpdatePassPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
